name: sonar-node-lts-repro

on:
  workflow_dispatch:

jobs:
  repro:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.job }}-${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.job }}-${{ github.run_number }}

      - run: |
          cat << EOF > Hello.java
            class HelloWorld {
              public static void main(String[] args) {
                System.out.println("hello world!");
              }
            }
          EOF
          docker run --rm -v $(pwd):/app -w /app maven:3.8.4-amazoncorretto-17 /bin/sh -c '
            java -version
            javac Hello.java

            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 16

            nvm ls
          '
