name: sonar-node-lts-repro

on:
  workflow_dispatch:

jobs:
  repro:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.job }}-${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.job }}-${{ github.run_number }}

      - run: |
          cat << EOF > pom.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion>

              <groupId>org.turtleyacht.hello</groupId>
              <artifactId>hello</artifactId>
              <version>0.0.1</version>
          </project>
          EOF

          cat << EOF > Hello.java
            class Hello {
              public static void main(String[] args) {
                System.out.println("hello world!");
              }
            }
          EOF

          touch sample.css

          docker run --rm -v $(pwd):/app -w /app maven:3.8.4-amazoncorretto-17 /bin/sh -c '
            java -version
            javac Hello.java
            java Hello

            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 16

            nvm ls

            mvn clean install \
              org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
              -Dsonar.host.url=*** \
              -Dsonar.organization=*** \
              -Dsonar.branch.name=*** \
              -Dsonar.projectKey=*** \
              -Dsonar.projectName=*** \
              -Dsonar.projectVersion=*** \
              -Dsonar.exclusions=**/*.config,**/*.css,**/*.html,**/*.ico,**/*.jar,**/*.js,**/*.json,**/*.md,**/*.properties,**/*.rss,**/*.scss,**/*.txt,**/*.ts,**/*.tsx,**/*.war,**/*.xml,**/*.yaml,**/*.yml
              -Dsonar.log.level=DEBUG \
              -Dsonar.verbose=true \
              -Dsonar.scm.exclusions.disabled=false \
              -Dsonar.nodejs.executable=/root/.nvm/versions/node/v16.20.2/bin/node  \
              -Dsonar.token=***
          '
